I think that the proper way to include BLAS/LAPACK libraries when using the intel compiler is through the Math Kernel Library (mkl) of Intel. Please Miguel check wether I changed properly the configure.ac file, it works in my computer but I am not an expert in those macros.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10275,6 +10275,49 @@ fi
 
 
 	if test -z "${LIB_BLAS}"; then
+		echo "$as_me:$LINENO: checking for ddot in -lmkl_lapack64" >&5
+echo $ECHO_N "checking for ddot in -lmkl_lapack64... $ECHO_C" >&6
+if test "${ac_cv_lib_mkl_lapack64_ddot+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmkl_lapack64 -lmkl_lapack32 -lmkl -lguide $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call ddot
+      end program main
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mkl_lapack64_ddot=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_mkl_lapack64_ddot=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mkl_lapack64_ddot" >&5
+echo "${ECHO_T}$ac_cv_lib_mkl_lapack64_ddot" >&6
+if test $ac_cv_lib_mkl_lapack64_ddot = yes; then
+  LIB_BLAS="-lmkl_lapack64 -lmkl_lapack32 -lmkl -lguide"
+fi
+
+	fi
+
+
+	if test -z "${LIB_BLAS}"; then
 		echo "$as_me:$LINENO: checking for ddot in -lf77blas" >&5
 echo $ECHO_N "checking for ddot in -lf77blas... $ECHO_C" >&6
 if test "${ac_cv_lib_f77blas_ddot+set}" = set; then
@@ -10658,6 +10701,49 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_cxml_dsygv" >&5
 echo "${ECHO_T}$ac_cv_lib_cxml_dsygv" >&6
 if test $ac_cv_lib_cxml_dsygv = yes; then
   LIB_LAPACK="-lcxml"
+fi
+
+	fi
+
+
+	if test -z "${LIB_LAPACK}"; then
+		echo "$as_me:$LINENO: checking for dsygv in -lmkl_lapack64" >&5
+echo $ECHO_N "checking for dsygv in -lmkl_lapack64... $ECHO_C" >&6
+if test "${ac_cv_lib_mkl_lapack64_dsygv+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmkl_lapack64 -lmkl_lapack32 -lmkl -lguide $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+      program main
+      call dsygv
+      end program main
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mkl_lapack64_dsygv=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_mkl_lapack64_dsygv=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mkl_lapack64_dsygv" >&5
+echo "${ECHO_T}$ac_cv_lib_mkl_lapack64_dsygv" >&6
+if test $ac_cv_lib_mkl_lapack64_dsygv = yes; then
+  LIB_LAPACK="-lmkl_lapack64 -lmkl_lapack32 -lmkl -lguide"
 fi
 
 	fi
